title: Environment
path: environment
type: 'custom:grid-layout'
layout: !include ui/shared/snippets/layout-page-margin.yaml
cards:
  - type: 'custom:layout-card'
    layout_type: 'custom:grid-layout'
    layout: !include ui/shared/snippets/layout-page-columns.yaml
    view_layout:
      grid-area: cc
    cards:

      - type: 'custom:layout-card'
        layout_type: 'custom:grid-layout'
        layout: !include ui/shared/snippets/layout-page-title.yaml
        view_layout:
          grid-column: 1/-1
        cards:
          - type: markdown
            style: !include ui/shared/snippets/style-markdown-page-title.yaml
            content: >
              # Environment
