title: Security
path: security
icon: 'mdi:shield-home'
type: 'custom:grid-layout'
layout: !include ../shared/snippets/layout-page-margin.yaml
cards:
  - type: 'custom:layout-card'
    layout_type: 'custom:grid-layout'
    layout: !include ../shared/snippets/layout-page-columns.yaml
    view_layout:
      grid-area: cc
    cards:

      - type: 'custom:layout-card'
        layout_type: 'custom:grid-layout'
        layout: !include ../shared/snippets/layout-page-title.yaml
        view_layout:
          grid-column: 1/-1
        cards:
          - type: markdown
            style: !include ../shared/snippets/style-markdown-page-title.yaml
            content: >
              # Security

      - type: 'custom:layout-card'
        layout_type: 'custom:grid-layout'
        layout: !include ../shared/snippets/layout-live-tile.yaml
        view_layout:
          grid-column: 1/-1
        cards:

          # [Safety]

          - type: 'custom:button-card'
            template: header_card_no_link
            variables:
              name: SAFETY
            view_layout:
              grid-column: 1/-1

          - type: 'custom:button-card'
            template: live_tile
            entity: binary_sensor.smoke_co_detector_carbon_monoxide_detected
            name: CO Detected
            icon: mdi:molecule-co

          - type: 'custom:button-card'
            template: live_tile
            entity: binary_sensor.smoke_co_detector_smoke_alarm_test
            name: Smoke Test
            icon: mdi:smoke-detector

          - type: 'custom:button-card'
            template: live_tile
            entity: binary_sensor.smoke_co_detector_alarm_silenced
            name: Alarm Silenced
            icon: mdi:bell-off

          - type: 'custom:button-card'
            template: live_tile
            entity: binary_sensor.keypad_ac_mains_disconnected
            name: Keypad AC
            icon: mdi:power-plug

          - type: 'custom:button-card'
            template: live_tile
            entity: binary_sensor.keypad_system_software_failure_with_failure_code
            name: Keypad SW Fault
            icon: mdi:alert-circle

          - type: 'custom:button-card'
            template: live_tile
            entity: binary_sensor.smoke_co_detector_smoke_detected
            name: Smoke Detected
            icon: mdi:smoke-detector-alert

          - type: 'custom:button-card'
            template: live_tile
            entity: binary_sensor.smoke_co_detector_replacement_required_end_of_life
            name: Detector EOL
            icon: mdi:smoke-detector-off

          - type: 'custom:button-card'
            template: live_tile
            entity: binary_sensor.siren_security_active
            name: Security Active
            icon: mdi:alarm-light

          # [Who's Home]

          - type: 'custom:button-card'
            template: header_card_no_link
            variables:
              name: WHO'S HOME
            view_layout:
              grid-column: 1/-1

          - type: 'custom:button-card'
            template: live_tile
            entity: person.jonathan_senecal
            name: Jonathan
            icon: mdi:account

          # [Outdoor]

          - type: 'custom:button-card'
            template: header_card_no_link
            variables:
              name: OUTDOOR
            view_layout:
              grid-column: 1/-1

          - type: 'custom:button-card'
            template: live_tile
            entity: binary_sensor.front_yard_motion
            name: Front Yard
            icon: mdi:motion-sensor

          - type: 'custom:button-card'
            template: live_tile
            entity: binary_sensor.back_yard_motion
            name: Back Yard
            icon: mdi:motion-sensor

          - type: 'custom:button-card'
            template: live_tile
            entity: binary_sensor.side_yard_motion
            name: Side Yard
            icon: mdi:motion-sensor

          - type: 'custom:button-card'
            template: live_tile
            entity: binary_sensor.driveway_is_dark
            name: Driveway Dark
            icon: mdi:weather-night

          - type: 'custom:button-card'
            template: live_tile
            entity: binary_sensor.front_yard_is_dark
            name: Front Yard Dark
            icon: mdi:weather-night

          - type: 'custom:button-card'
            template: live_tile
            entity: binary_sensor.back_yard_is_dark
            name: Back Yard Dark
            icon: mdi:weather-night

          - type: 'custom:button-card'
            template: live_tile
            entity: binary_sensor.side_yard_is_dark
            name: Side Yard Dark
            icon: mdi:weather-night

          - type: 'custom:button-card'
            template: live_tile
            entity: binary_sensor.front_door_is_dark
            name: Front Door Dark
            icon: mdi:weather-night

          - type: 'custom:button-card'
            template: live_tile
            entity: binary_sensor.front_door_doorbell
            name: Doorbell
            icon: mdi:doorbell

          - type: 'custom:button-card'
            template: live_tile
            entity: binary_sensor.front_door_motion
            name: Front Door Motion
            icon: mdi:motion-sensor

          # [Doors & Windows]

          - type: 'custom:button-card'
            template: header_card_no_link
            variables:
              name: DOORS & WINDOWS
            view_layout:
              grid-column: 1/-1

          - type: 'custom:button-card'
            template: live_tile
            entity: binary_sensor.front_door_lock_lock_jammed
            name: Front Lock
            icon: mdi:door-closed-lock

          - type: 'custom:button-card'
            template: live_tile
            entity: binary_sensor.front_door_lock_replace_battery_soon
            name: Lock Battery
            icon: mdi:battery-low

          - type: 'custom:button-card'
            template: live_tile
            entity: binary_sensor.front_door_lock_system_hardware_failure
            name: Lock HW Fault
            icon: mdi:lock-alert

          - type: 'custom:button-card'
            template: live_tile
            entity: binary_sensor.patio_door_contact
            name: Patio Door
            icon: mdi:door-sliding

          - type: 'custom:button-card'
            template: live_tile
            entity: binary_sensor.patio_screen_door_contact
            name: Screen Door
            icon: mdi:door-sliding

          - type: 'custom:button-card'
            template: live_tile
            entity: binary_sensor.office_door_sensor_contact
            name: Office Door
            icon: mdi:door

          - type: 'custom:button-card'
            template: live_tile
            entity: binary_sensor.office_window_contact
            name: Office Window
            icon: mdi:window-open

          - type: 'custom:button-card'
            template: live_tile
            entity: binary_sensor.laundry_room_door_contact
            name: Laundry Door
            icon: mdi:door

          # [Water]

          - type: 'custom:button-card'
            template: header_card_no_link
            variables:
              name: WATER
            view_layout:
              grid-column: 1/-1

          - type: 'custom:button-card'
            template: live_tile
            entity: binary_sensor.kitchen_sink_water_leak_sensor_water_leak
            name: Kitchen Sink
            icon: mdi:water-alert

          - type: 'custom:button-card'
            template: live_tile
            entity: binary_sensor.filter_leak_sensor_water_leak
            name: Filter
            icon: mdi:water-alert

          - type: 'custom:button-card'
            template: live_tile
            entity: switch.main_valve_shutoff_valve
            name: Shutoff Valve
            icon: mdi:valve

          - type: 'custom:button-card'
            template: live_tile
            entity: binary_sensor.main_valve_pending_system_alerts
            name: Main Valve
            icon: mdi:pipe-valve

          - type: 'custom:button-card'
            template: live_tile_with_unit
            entity: sensor.main_valve_water_flow_rate
            name: Flow Rate
            icon: mdi:water-pump

          - type: 'custom:button-card'
            template: live_tile_with_unit
            entity: sensor.main_valve_water_pressure
            name: Pressure
            icon: mdi:gauge

          - type: 'custom:button-card'
            template: live_tile_with_unit
            entity: sensor.main_valve_today_s_water_usage
            name: Today Usage
            icon: mdi:water
            view_layout:
              grid-column: span 2

          # [Occupancy]

          - type: 'custom:button-card'
            template: header_card_no_link
            variables:
              name: OCCUPANCY
            view_layout:
              grid-column: 1/-1

          - type: 'custom:button-card'
            template: live_tile
            entity: binary_sensor.kitchen_dimmer_2_occupancy
            name: Kitchen
            icon: mdi:motion-sensor

          - type: 'custom:button-card'
            template: live_tile
            entity: binary_sensor.great_room_motion
            name: Great Room
            icon: mdi:motion-sensor

          - type: 'custom:button-card'
            template: live_tile
            entity: binary_sensor.great_room_presence_sensor_occupancy
            name: Great Room Pres
            icon: mdi:radar

          - type: 'custom:button-card'
            template: live_tile
            entity: binary_sensor.office_motion_occupancy
            name: Office Motion
            icon: mdi:motion-sensor

          - type: 'custom:button-card'
            template: live_tile
            entity: binary_sensor.office_presence_sensor_occupancy
            name: Office Pres
            icon: mdi:radar

          - type: 'custom:button-card'
            template: live_tile
            entity: binary_sensor.albert_s_bedroom_motion
            name: Albert's Rm
            icon: mdi:motion-sensor

          - type: 'custom:button-card'
            template: live_tile
            entity: binary_sensor.aude_s_bedroom_motion
            name: Aude's Rm
            icon: mdi:motion-sensor

          - type: 'custom:button-card'
            template: live_tile
            entity: binary_sensor.family_room_motion
            name: Family Room
            icon: mdi:motion-sensor

          - type: 'custom:button-card'
            template: live_tile
            entity: binary_sensor.0x282c02bfffe8009c_occupancy
            name: Server Room
            icon: mdi:motion-sensor

          - type: 'custom:button-card'
            template: live_tile
            entity: binary_sensor.0x8c6fb9fffe3c75a9_occupancy
            name: Laundry Room
            icon: mdi:motion-sensor

          # [Appliances]

          - type: 'custom:button-card'
            template: header_card_no_link
            variables:
              name: APPLIANCES
            view_layout:
              grid-column: 1/-1

          - type: 'custom:button-card'
            template: live_tile
            entity: binary_sensor.refrigerator_running
            name: Refrigerator
            icon: mdi:fridge

          - type: 'custom:button-card'
            template: live_tile
            entity: binary_sensor.washing_machine_s31_washing_machine_running
            name: Washing Machine
            icon: mdi:washing-machine
